/- Copyright (c) 2026 the lean-tcb contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE. -/
import Lean
import LeanTcb.Types
import LeanTcb.Attr

/-!
# Output formatting

Groups the raw `TcbResult` into user-facing categories (axioms,
user specification, library dependencies) and renders them for
the Lean infoview.
-/

open Lean

namespace LeanTcb

/-- Standard axioms that ship with Lean's core.
    These have been stable across all Lean 4 versions through
    v4.27.0. There is no Lean API to query "standard" axioms
    dynamically, so they are hardcoded here.
    Revisit on major Lean version bumps. -/
private def standardAxioms : Lean.NameSet :=
  ({} : Lean.NameSet)
    |>.insert `propext
    |>.insert `Classical.choice
    |>.insert `Quot.sound

/-- Whether a declaration belongs to the same Lake package as the
    current module (i.e., is "project-local" rather than from an
    external library dependency). Declarations defined in the
    current file (no module index) are always project-local. -/
def isProjectLocal (env : Environment) (n : Name) : Bool :=
  match env.getModuleIdxFor? n with
  | none => true  -- defined in the current file
  | some idx =>
    -- Compare package IDs; none = bootstrap/core = external
    match env.getModulePackageByIdx? idx, env.getModulePackage? with
    | some pkg, some currentPkg => pkg == currentPkg
    | _, _ => false

/-- Short label for a declaration's kind. -/
def declKindLabel (ci : ConstantInfo) : String :=
  match ci with
  | .defnInfo v =>
    match v.hints with
    | .abbrev => "abbrev"
    | _ => "def"
  | .thmInfo _    => "theorem"
  | .axiomInfo _  => "axiom"
  | .opaqueInfo _ => "opaque"
  | .inductInfo _ => "inductive"
  | .ctorInfo _   => "constructor"
  | .recInfo _    => "recursor"
  | .quotInfo _   => "quot"

/-- Whether a name's leaf component is auto-generated by the
    Lean elaborator (inductives, pattern matching, etc.).
    These inflate the "% of project" denominator.

    This list is necessarily incomplete — Lean may generate
    new auxiliary names in future versions. The safe direction:
    missing an auto-generated name slightly inflates the
    percentage but never hides a real dependency. -/
def isAutoGenerated (n : Name) : Bool :=
  match n with
  | .num _ _ => true
  | .str _ s =>
    s == "rec" || s == "recOn" || s == "casesOn" ||
    s == "brecOn" || s == "noConfusion" ||
    s == "noConfusionType" || s == "below" ||
    s == "ibelow" || s == "binductionOn" ||
    s == "injEq" || s == "mk" ||
    s == "ndrec" || s == "ndrecOn" ||
    s == "sizeOf_spec" || s == "toCtorIdx"
  | .anonymous => false

/-- Singular or plural form based on count. -/
private def pluralize (n : Nat) (singular plural : String)
    : String :=
  if n == 1 then singular else plural

/-- Categorized output for display. -/
structure FormattedResult where
  /-- Entry-point names that seeded the analysis. -/
  entryPoints : Array Name
  /-- Axioms in the spec set, with standard/non-standard kind. -/
  axioms : Array (Name × AxiomKind)
  /-- Current-module declarations in the spec set. -/
  userSpec : Array (Name × String)
  /-- Imported declarations in the spec set. -/
  librarySpec : Array Name
  /-- Current-module declarations NOT in the spec set. -/
  userNotInTcb : Nat
  /-- Human-written TCB count (excludes auto-generated). -/
  humanSpecCount : Nat := 0
  /-- Human-written non-TCB count. -/
  humanNotInTcb : Nat := 0
  /-- Warnings about soundness issues (sorry, native_decide, etc.). -/
  warnings : Array String := #[]
  deriving Inhabited

instance : ToString FormattedResult where
  toString fr :=
    s!"FormattedResult(entryPoints={fr.entryPoints.size}, \
      axioms={fr.axioms.size}, \
      userSpec={fr.userSpec.size}, \
      librarySpec={fr.librarySpec.size}, \
      userNotInTcb={fr.userNotInTcb})"

/-- Format a `TcbResult` into categorized groups for display.
    `allUserDecls` should contain all declaration names from
    the current module. -/
def formatResult (env : Environment) (result : TcbResult)
    (allUserDecls : Array Name) : FormattedResult :=
    Id.run do
  let mut axioms : Array (Name × AxiomKind) := #[]
  let mut userSpec : Array (Name × String) := #[]
  let mut librarySpec : Array Name := #[]

  for name in result.specSet do
    match env.find? name with
    | some ci =>
      if ci matches .axiomInfo _ then
        let kind : AxiomKind :=
          if standardAxioms.contains name then .standard
          else .nonStandard
        axioms := axioms.push (name, kind)
      else if isProjectLocal env name then
        userSpec := userSpec.push (name, declKindLabel ci)
      else
        librarySpec := librarySpec.push name
    | none => ()

  let mut userNotInTcb : Nat := 0
  let mut humanNotInTcb : Nat := 0
  for name in allUserDecls do
    unless result.specSet.contains name do
      userNotInTcb := userNotInTcb + 1
      unless isAutoGenerated name do
        humanNotInTcb := humanNotInTcb + 1

  let mut humanSpecCount : Nat := 0
  for (name, _) in userSpec do
    unless isAutoGenerated name do
      humanSpecCount := humanSpecCount + 1

  return {
    entryPoints := result.entryPoints
    axioms := axioms.qsort (fun a b => Name.lt a.1 b.1)
    userSpec := userSpec.qsort (fun a b => Name.lt a.1 b.1)
    librarySpec := librarySpec.qsort Name.lt
    userNotInTcb
    humanSpecCount
    humanNotInTcb
  }

/-- Render a formatted result as a string for the infoview.
    Set `verbose` to include the full library dependency listing.
    Pass `annCheck` to include annotation cross-check results. -/
def renderResult (fr : FormattedResult)
    (verbose : Bool := false)
    (annCheck : Option AnnotationCheck := none)
    (env : Option Environment := none)
    : String := Id.run do
  let mut lines : Array String := #[]

  lines := lines.push "═══ TCB Analysis ═══"
  lines := lines.push ""

  -- Entry points
  let epStr := String.intercalate ", "
    (fr.entryPoints.map Name.toString).toList
  lines := lines.push s!"Entry points: {epStr}"
  lines := lines.push ""

  -- Must review
  if fr.userSpec.isEmpty && fr.entryPoints.size > 0 then
    lines := lines.push "── Must Review ──"
    lines := lines.push
      "  (all entry points are library declarations \
        — no project-local TCB)"
    lines := lines.push ""

  if fr.userSpec.size > 0 then
    -- Partition into human-written and auto-generated
    let humanSpec := fr.userSpec.filter
      (fun (n, _) => !isAutoGenerated n)
    let autoGenSpec := fr.userSpec.filter
      (fun (n, _) => isAutoGenerated n)
    let n := humanSpec.size
    let dw := pluralize n "declaration" "declarations"
    lines := lines.push s!"── Must Review ({n} {dw}) ──"
    let maxLen := fr.userSpec.foldl
      (fun acc (n, _) => max acc (toString n).length) 0
    -- Compute max kind label length for alignment
    let maxKindLen := fr.userSpec.foldl
      (fun acc (_, k) => max acc k.length) 0
    for (name, kind) in humanSpec do
      let nameStr := toString name
      let pad := maxLen - nameStr.length + 2
      let padding :=
        String.ofList (List.replicate pad ' ')
      let kindPad := maxKindLen - kind.length
      let modStr := match env with
        | some e =>
          match e.getModuleIdxFor? name with
          | none => ""
          | some idx =>
            match e.header.moduleNames[idx]? with
            | some modName =>
              let kp := String.ofList
                (List.replicate (kindPad + 2) ' ')
              s!"{kp}({modName})"
            | none => ""
        | none => ""
      lines := lines.push
        s!"  • {nameStr}{padding}{kind}{modStr}"
    if autoGenSpec.size > 0 then
      lines := lines.push "  Auto-generated:"
      for (name, kind) in autoGenSpec do
        let nameStr := toString name
        let pad := maxLen - nameStr.length + 2
        let padding :=
          String.ofList (List.replicate pad ' ')
        lines := lines.push
          s!"    {nameStr}{padding}{kind}"
    lines := lines.push ""

  -- Axioms
  let (stdAxioms, nonStdAxioms) :=
    fr.axioms.partition (·.2 == .standard)
  lines := lines.push "── Axioms ──"
  if nonStdAxioms.size > 0 then
    lines := lines.push s!"  {nonStdAxioms.size} non-standard:"
    for (name, _) in nonStdAxioms do
      lines := lines.push s!"    ⚠ {name}"
  if stdAxioms.size > 0 then
    let names := stdAxioms.map (fun (n, _) => toString n)
    let joined := String.intercalate ", " names.toList
    lines := lines.push s!"  {stdAxioms.size} standard ({joined})"
  if fr.axioms.size == 0 then
    lines := lines.push "  none"
  lines := lines.push ""

  -- Library spec (verbose only)
  if verbose && fr.librarySpec.size > 0 then
    let n := fr.librarySpec.size
    let dw := pluralize n "declaration" "declarations"
    lines := lines.push
      s!"── Library Dependencies ({n} {dw}) ──"
    for name in fr.librarySpec do
      lines := lines.push s!"  • {name}"
    lines := lines.push ""

  -- Annotation check
  if let some ac := annCheck then
    if ac.hasAnnotations then
      lines := lines.push "── @[tcb] Annotation Check ──"
      if ac.unannotated.size > 0 then
        let n := ac.unannotated.size
        lines := lines.push
          s!"  {n} in TCB but not annotated \
            (consider adding @[tcb]):"
        for name in ac.unannotated do
          lines := lines.push s!"    ⚠ {name}"
      if ac.unnecessary.size > 0 then
        let n := ac.unnecessary.size
        lines := lines.push
          s!"  {n} annotated but not in TCB \
            for these entry points:"
        for name in ac.unnecessary do
          lines := lines.push s!"    ✗ {name}"
      if ac.unannotated.isEmpty && ac.unnecessary.isEmpty then
        lines := lines.push
          "  ✓ All @[tcb] annotations match the TCB"
      lines := lines.push ""

  -- Warnings
  if fr.warnings.size > 0 then
    lines := lines.push "── Warnings ──"
    for w in fr.warnings do
      lines := lines.push s!"  ⚠ {w}"
    lines := lines.push ""

  -- Summary
  let humanTotal := fr.humanSpecCount + fr.humanNotInTcb
  let autoGenCount := fr.userSpec.size - fr.humanSpecCount
  lines := lines.push "── Summary ──"
  let pctStr := if humanTotal > 0
    then
      s!" ({fr.humanSpecCount * 100 / humanTotal}% \
        of project)"
    else ""
  let hsc := fr.humanSpecCount
  let dw := pluralize hsc "declaration" "declarations"
  lines := lines.push
    s!"  Must review:    {hsc} {dw}{pctStr}"
  if autoGenCount > 0 then
    let agDw := pluralize autoGenCount
      "declaration" "declarations"
    lines := lines.push
      s!"  Auto-generated: {autoGenCount} {agDw}"
  let nitDw := pluralize fr.userNotInTcb
    "declaration" "declarations"
  lines := lines.push
    s!"  Not in TCB:     {fr.userNotInTcb} {nitDw}"
  let libDw := pluralize fr.librarySpec.size
    "dependency" "dependencies"
  lines := lines.push
    s!"  Depends on:     {fr.librarySpec.size} \
      library {libDw}"

  -- Discoverability tip (only when there are user-spec entries)
  if fr.userSpec.size > 0 then
    lines := lines.push ""
    lines := lines.push
      "Tip: #tcb_tree for dependency graph · \
        #tcb_why <entry> <name> to trace a path"

  return String.intercalate "\n" lines.toList

end LeanTcb
